apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
      <title>Helm deployment</title>
    </head>
    <body>
      <h1>Hello from the first helm deployment!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-first
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: hello-kubernetes-first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-first
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-kubernetes-first
  template:
    metadata:
      labels:
        app: hello-kubernetes-first
    spec:
      containers:
      - name: hello-kubernetes
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html/
      volumes:
      - name: html-volume
        configMap:
          name: my-configmap
